/**
 * StayNest — Comprehensive Seed Script
 * Adds 5 listings per category (55 total) to the LIVE Atlas DB.
 * Run: node init/seed.js
 */

require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const mongoose = require('mongoose');
const Listing  = require('../models/listing.js');

const DB_URL = process.env.ATLAS_URL;
if (!DB_URL) { console.error('❌  ATLAS_URL missing from .env'); process.exit(1); }

// ── Seed Data ──────────────────────────────────────────────────────────────
const listings = [

  // ── TRENDING ──────────────────────────────────────────────────────────────
  {
    title: 'Luxury Villa in North Goa',
    description: 'Stunning beachside villa with private pool, lush gardens, and breathtaking sunset views over the Arabian Sea.',
    price: 18000,
    location: 'Calangute, North Goa',
    country: 'India',
    category: 'Trending',
    maxGuests: 8,
    amenities: ['Wifi', 'Pool', 'Kitchen', 'Free Parking', 'AC', 'TV'],
    geometry: { type: 'Point', coordinates: [73.8278, 15.5443] },
    image: { url: 'https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Heritage Riad in Jaipur Pink City',
    description: 'A restored 200-year-old haveli in the old walled city, with hand-painted frescoes and a rooftop terrace.',
    price: 12000,
    location: 'Jaipur Old City, Rajasthan',
    country: 'India',
    category: 'Trending',
    maxGuests: 6,
    amenities: ['Wifi', 'AC', 'Kitchen', 'TV'],
    geometry: { type: 'Point', coordinates: [75.8235, 26.9124] },
    image: { url: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Cliffside Suite in Santorini',
    description: 'Iconic white-and-blue suite carved into the volcanic caldera with an infinity pool and caldera views.',
    price: 42000,
    location: 'Oia, Santorini',
    country: 'Greece',
    category: 'Trending',
    maxGuests: 2,
    amenities: ['Wifi', 'Pool', 'AC', 'TV'],
    geometry: { type: 'Point', coordinates: [25.3753, 36.4618] },
    image: { url: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Bali Jungle Retreat',
    description: 'An open-air villa nestled inside a tropical jungle with a private plunge pool and dedicated yoga shala.',
    price: 9500,
    location: 'Ubud, Bali',
    country: 'Indonesia',
    category: 'Trending',
    maxGuests: 4,
    amenities: ['Wifi', 'Pool', 'Kitchen', 'AC'],
    geometry: { type: 'Point', coordinates: [115.2625, -8.5069] },
    image: { url: 'https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Treehouse Escape in Munnar',
    description: 'Award-winning treehouse high in the tea estates of Munnar with panoramic valley views and misty mornings.',
    price: 8500,
    location: 'Munnar, Kerala',
    country: 'India',
    category: 'Trending',
    maxGuests: 2,
    amenities: ['Wifi', 'AC', 'TV'],
    geometry: { type: 'Point', coordinates: [77.0607, 10.0889] },
    image: { url: 'https://images.unsplash.com/photo-1488462237308-ecaa28b729d7?w=1200&auto=format&fit=crop', filename: 'seed' },
  },

  // ── ROOMS ────────────────────────────────────────────────────────────────
  {
    title: 'Cosy Studio near Indiranagar, Bengaluru',
    description: 'Bright, clean private studio in the heart of Indiranagar. Walking distance to cafes, restaurants and the metro.',
    price: 2200,
    location: 'Indiranagar, Bengaluru',
    country: 'India',
    category: 'Rooms',
    maxGuests: 2,
    amenities: ['Wifi', 'AC', 'Kitchen', 'TV', 'Washing Machine'],
    geometry: { type: 'Point', coordinates: [77.6413, 12.9784] },
    image: { url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Designer Room in Bandra West',
    description: 'Stylish private room in a modern apartment, minutes from Bandstand promenade and Mumbai\'s best eateries.',
    price: 3200,
    location: 'Bandra West, Mumbai',
    country: 'India',
    category: 'Rooms',
    maxGuests: 2,
    amenities: ['Wifi', 'AC', 'TV'],
    geometry: { type: 'Point', coordinates: [72.8296, 19.0596] },
    image: { url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Peaceful Room in Pondicherry White Town',
    description: 'French colonial-era room with high ceilings, wooden floors and a private balcony in the serene White Town.',
    price: 1800,
    location: 'White Town, Pondicherry',
    country: 'India',
    category: 'Rooms',
    maxGuests: 2,
    amenities: ['Wifi', 'AC', 'Kitchen'],
    geometry: { type: 'Point', coordinates: [79.8349, 11.9340] },
    image: { url: 'https://images.unsplash.com/photo-1505693314120-0d443867891c?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Lake-View Room in Udaipur',
    description: 'Wake up to views of Lake Pichola from your private room in a charming guesthouse near the City Palace.',
    price: 2800,
    location: 'Gangaur Ghat, Udaipur',
    country: 'India',
    category: 'Rooms',
    maxGuests: 2,
    amenities: ['Wifi', 'AC', 'TV'],
    geometry: { type: 'Point', coordinates: [73.6833, 24.5754] },
    image: { url: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Budget Room in Paharganj, Delhi',
    description: 'Clean and centrally located private room in New Delhi\'s famous backpacker hub, near New Delhi Railway Station.',
    price: 1200,
    location: 'Paharganj, New Delhi',
    country: 'India',
    category: 'Rooms',
    maxGuests: 2,
    amenities: ['Wifi', 'AC', 'TV'],
    geometry: { type: 'Point', coordinates: [77.2090, 28.6449] },
    image: { url: 'https://images.unsplash.com/photo-1541123437800-1bb1317badc2?w=1200&auto=format&fit=crop', filename: 'seed' },
  },

  // ── ICONIC CITIES ─────────────────────────────────────────────────────────
  {
    title: 'Central Park West Apartment, NYC',
    description: "Pre-war luxury apartment overlooking Central Park with original details, a chef's kitchen, and skyline views.",
    price: 55000,
    location: 'Upper West Side, New York',
    country: 'USA',
    category: 'Iconic Cities',
    maxGuests: 4,
    amenities: ['Wifi', 'Kitchen', 'AC', 'TV', 'Dedicated Workspace'],
    geometry: { type: 'Point', coordinates: [-73.9798, 40.7831] },
    image: { url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Haussmann Apartment near the Eiffel Tower',
    description: 'Classic 19th-century Parisian apartment with original parquet floors, ornate mouldings, and Eiffel Tower views.',
    price: 38000,
    location: 'Trocadéro, Paris',
    country: 'France',
    category: 'Iconic Cities',
    maxGuests: 4,
    amenities: ['Wifi', 'Kitchen', 'AC', 'TV'],
    geometry: { type: 'Point', coordinates: [2.2902, 48.8651] },
    image: { url: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Shoreditch Loft in East London',
    description: 'Industrial-chic converted warehouse loft in the heart of London\'s creative district, minutes from Brick Lane.',
    price: 28000,
    location: 'Shoreditch, London',
    country: 'United Kingdom',
    category: 'Iconic Cities',
    maxGuests: 4,
    amenities: ['Wifi', 'Kitchen', 'TV', 'Washing Machine'],
    geometry: { type: 'Point', coordinates: [-0.0793, 51.5227] },
    image: { url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Penthouse in South Mumbai',
    description: 'Lavish penthouse with panoramic views of the Arabian Sea and Marine Drive from the 32nd floor.',
    price: 45000,
    location: 'Marine Drive, Mumbai',
    country: 'India',
    category: 'Iconic Cities',
    maxGuests: 6,
    amenities: ['Wifi', 'Pool', 'Kitchen', 'AC', 'TV', 'Dedicated Workspace'],
    geometry: { type: 'Point', coordinates: [72.8232, 18.9440] },
    image: { url: 'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Tokyo Shibuya Modern Suite',
    description: 'Sleek minimalist suite 5 minutes from the iconic Shibuya Crossing, with high-speed internet and Japanese-style bathtub.',
    price: 22000,
    location: 'Shibuya, Tokyo',
    country: 'Japan',
    category: 'Iconic Cities',
    maxGuests: 2,
    amenities: ['Wifi', 'Kitchen', 'AC', 'TV', 'Self Check-in'],
    geometry: { type: 'Point', coordinates: [139.7006, 35.6580] },
    image: { url: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&auto=format&fit=crop', filename: 'seed' },
  },

  // ── MOUNTAINS ─────────────────────────────────────────────────────────────
  {
    title: 'Pine-Forest Chalet in Manali',
    description: 'Secluded wooden chalet surrounded by deodar forests with views of the Beas River and snow-capped peaks.',
    price: 7500,
    location: 'Old Manali, Himachal Pradesh',
    country: 'India',
    category: 'Mountains',
    maxGuests: 6,
    amenities: ['Wifi', 'Kitchen', 'TV', 'Free Parking'],
    geometry: { type: 'Point', coordinates: [77.1892, 32.2396] },
    image: { url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Alpine Cabin in Swiss Alps',
    description: 'Traditional Swiss alpine cabin at 1,800m with direct ski-in/ski-out access and wood-burning fireplace.',
    price: 48000,
    location: 'Zermatt, Valais',
    country: 'Switzerland',
    category: 'Mountains',
    maxGuests: 8,
    amenities: ['Wifi', 'Kitchen', 'TV', 'Free Parking'],
    geometry: { type: 'Point', coordinates: [7.7491, 46.0207] },
    image: { url: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Himalayan Homestay in Spiti Valley',
    description: "Authentic mud-brick homestay in one of India's most remote valleys at 4,000m. Experience Lahauli culture.",
    price: 3500,
    location: 'Kaza, Spiti Valley',
    country: 'India',
    category: 'Mountains',
    maxGuests: 4,
    amenities: ['Kitchen', 'Free Parking'],
    geometry: { type: 'Point', coordinates: [78.0726, 32.2276] },
    image: { url: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Mountain View Cottage in Darjeeling',
    description: 'Victorian-era cottage on a hill tea garden with sunrise views of Kanchenjunga and the Himalayan range.',
    price: 5500,
    location: 'Jorebunglow, Darjeeling',
    country: 'India',
    category: 'Mountains',
    maxGuests: 4,
    amenities: ['Wifi', 'Kitchen', 'TV'],
    geometry: { type: 'Point', coordinates: [88.2627, 27.0361] },
    image: { url: 'https://images.unsplash.com/photo-1527489377706-5bf97e608852?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Rocky Mountain Retreat, Colorado',
    description: 'Stunning log home on 5 private acres with hot tub, outdoor fire pit, and elk sightings at your doorstep.',
    price: 32000,
    location: 'Breckenridge, Colorado',
    country: 'USA',
    category: 'Mountains',
    maxGuests: 10,
    amenities: ['Wifi', 'Kitchen', 'TV', 'Free Parking', 'Pool'],
    geometry: { type: 'Point', coordinates: [-106.0384, 39.4817] },
    image: { url: 'https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=1200&auto=format&fit=crop', filename: 'seed' },
  },

  // ── CASTLES ───────────────────────────────────────────────────────────────
  {
    title: 'Scottish Baronial Tower House',
    description: 'A private 12th-century Scottish tower house with a great hall, spiral staircase and Highland views.',
    price: 65000,
    location: 'Perthshire, Scotland',
    country: 'United Kingdom',
    category: 'Castles',
    maxGuests: 12,
    amenities: ['Wifi', 'Kitchen', 'Free Parking', 'TV'],
    geometry: { type: 'Point', coordinates: [-3.7953, 56.4107] },
    image: { url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Loire Valley Château',
    description: 'Sleep like royalty in this 15th-century French château surrounded by formal gardens and vineyards.',
    price: 72000,
    location: 'Amboise, Loire Valley',
    country: 'France',
    category: 'Castles',
    maxGuests: 14,
    amenities: ['Wifi', 'Kitchen', 'Pool', 'Free Parking', 'TV'],
    geometry: { type: 'Point', coordinates: [0.9817, 47.4131] },
    image: { url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Medieval Castle in Rajasthan',
    description: 'Stay inside a real 14th-century fort perched on a rocky hill in the Aravalli hills of Rajasthan.',
    price: 28000,
    location: 'Kumbhalgarh, Rajasthan',
    country: 'India',
    category: 'Castles',
    maxGuests: 10,
    amenities: ['Wifi', 'AC', 'Pool', 'Free Parking', 'TV', 'Kitchen'],
    geometry: { type: 'Point', coordinates: [73.5871, 25.1485] },
    image: { url: 'https://images.unsplash.com/photo-1519181245277-cffeb31da2e3?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Irish Romantic Castle Estate',
    description: 'A fairy-tale turreted castle in the West of Ireland with 40 acres of grounds, its own lake and boat.',
    price: 88000,
    location: 'Connemara, County Galway',
    country: 'Ireland',
    category: 'Castles',
    maxGuests: 16,
    amenities: ['Wifi', 'Kitchen', 'Free Parking', 'TV'],
    geometry: { type: 'Point', coordinates: [-9.5288, 53.4924] },
    image: { url: 'https://images.unsplash.com/photo-1604580864964-0462f5d5b1a8?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Portuguese Palace in Sintra',
    description: 'A Moorish-revival palace from 1850 set in the UNESCO-listed Sintra Cultural Landscape. The stuff of dreams.',
    price: 58000,
    location: 'Sintra, Lisbon Region',
    country: 'Portugal',
    category: 'Castles',
    maxGuests: 10,
    amenities: ['Wifi', 'Kitchen', 'Pool', 'Free Parking', 'TV', 'AC'],
    geometry: { type: 'Point', coordinates: [-9.3917, 38.7978] },
    image: { url: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=1200&auto=format&fit=crop', filename: 'seed' },
  },

  // ── AMAZING POOLS ─────────────────────────────────────────────────────────
  {
    title: 'Overwater Villa in Maldives',
    description: 'Iconic overwater bungalow with glass floor panels, direct lagoon access and your own infinity pool above the sea.',
    price: 95000,
    location: 'North Malé Atoll, Maldives',
    country: 'Maldives',
    category: 'Amazing Pools',
    maxGuests: 2,
    amenities: ['Wifi', 'Pool', 'AC', 'TV', 'Kitchen'],
    geometry: { type: 'Point', coordinates: [73.5213, 4.1755] },
    image: { url: 'https://images.unsplash.com/photo-1439130490301-25e322d88054?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Infinity Pool Villa in Koh Samui',
    description: 'Hilltop villa with a 25m infinity pool that seemingly merges with the Gulf of Thailand. Total luxury.',
    price: 52000,
    location: 'Chaweng Noi, Koh Samui',
    country: 'Thailand',
    category: 'Amazing Pools',
    maxGuests: 8,
    amenities: ['Wifi', 'Pool', 'Kitchen', 'AC', 'TV'],
    geometry: { type: 'Point', coordinates: [100.0600, 9.5225] },
    image: { url: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Private Pool Estate in Alibag',
    description: 'Weekend gateway from Mumbai – a 3-acre estate with temperature-controlled pool, volleyball court and organic farm.',
    price: 22000,
    location: 'Alibag, Maharashtra',
    country: 'India',
    category: 'Amazing Pools',
    maxGuests: 12,
    amenities: ['Wifi', 'Pool', 'Kitchen', 'Free Parking', 'AC', 'TV'],
    geometry: { type: 'Point', coordinates: [72.8777, 18.6414] },
    image: { url: 'https://images.unsplash.com/photo-1540541338537-1220059a8b84?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Rooftop Pool Apartment in Barcelona',
    description: 'Penthouse with private rooftop pool and 360° views over Barcelona, minutes from Park Güell.',
    price: 38000,
    location: 'Gràcia, Barcelona',
    country: 'Spain',
    category: 'Amazing Pools',
    maxGuests: 4,
    amenities: ['Wifi', 'Pool', 'Kitchen', 'AC', 'TV'],
    geometry: { type: 'Point', coordinates: [2.1534, 41.4036] },
    image: { url: 'https://images.unsplash.com/photo-1495365200479-c4ed1d35e1aa?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Pool Villa in South Goa',
    description: 'Tranquil 4-bedroom villa with private pool, in a secluded lane near the laid-back beaches of Palolem.',
    price: 16000,
    location: 'Palolem, South Goa',
    country: 'India',
    category: 'Amazing Pools',
    maxGuests: 8,
    amenities: ['Wifi', 'Pool', 'Kitchen', 'Free Parking', 'AC'],
    geometry: { type: 'Point', coordinates: [74.0232, 15.0101] },
    image: { url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop', filename: 'seed' },
  },

  // ── CAMPING ───────────────────────────────────────────────────────────────
  {
    title: 'Glamping Tent in Jim Corbett',
    description: 'Luxury safari tent on the fringe of Corbett National Park — elephant sightings at sunrise from your private deck.',
    price: 6500,
    location: 'Dhikala Zone, Jim Corbett',
    country: 'India',
    category: 'Camping',
    maxGuests: 2,
    amenities: ['Wifi', 'Free Parking', 'TV'],
    geometry: { type: 'Point', coordinates: [78.7745, 29.5357] },
    image: { url: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Desert Camp under the Stars, Jaisalmer',
    description: 'Sleep in a decorated Rajasthani tent in the Sam Sand Dunes with live folk music, camel safari and fire.',
    price: 4500,
    location: 'Sam Sand Dunes, Jaisalmer',
    country: 'India',
    category: 'Camping',
    maxGuests: 2,
    amenities: ['Kitchen', 'Free Parking'],
    geometry: { type: 'Point', coordinates: [70.5872, 26.9157] },
    image: { url: 'https://images.unsplash.com/photo-1494500764479-0c8f2919a3d8?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Yosemite Valley Campsite Cabin',
    description: 'Rustic off-grid cabin on the edge of Yosemite with a wood stove, bear box and stunning valley views.',
    price: 18000,
    location: 'Yosemite Valley, California',
    country: 'USA',
    category: 'Camping',
    maxGuests: 4,
    amenities: ['Kitchen', 'Free Parking'],
    geometry: { type: 'Point', coordinates: [-119.5383, 37.7456] },
    image: { url: 'https://images.unsplash.com/photo-1455763916899-e8b50eca9967?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Riverside Eco Camp in Coorg',
    description: 'Canvas tents alongside the Cauvery river in a coffee plantation — bonfire nights, kayaking and birdwatching.',
    price: 3800,
    location: 'Galibeedu, Coorg',
    country: 'India',
    category: 'Camping',
    maxGuests: 4,
    amenities: ['Kitchen', 'Free Parking'],
    geometry: { type: 'Point', coordinates: [75.7804, 12.3375] },
    image: { url: 'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Norwegian Fjord Basecamp',
    description: 'Base camp-style cabin perched above a stunning Norwegian fjord, ideal for hiking and Northern Lights viewing.',
    price: 28000,
    location: 'Flåm, Aurlandfjord',
    country: 'Norway',
    category: 'Camping',
    maxGuests: 4,
    amenities: ['Wifi', 'Kitchen', 'Free Parking'],
    geometry: { type: 'Point', coordinates: [7.1271, 60.8634] },
    image: { url: 'https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=1200&auto=format&fit=crop', filename: 'seed' },
  },

  // ── FARMS ─────────────────────────────────────────────────────────────────
  {
    title: 'Organic Coffee Farm Stay in Chikmagalur',
    description: 'Live on a 200-acre organic coffee estate, participate in the harvest, and sip fresh-roasted coffee at sunrise.',
    price: 5200,
    location: 'Chikmagalur, Karnataka',
    country: 'India',
    category: 'Farms',
    maxGuests: 4,
    amenities: ['Wifi', 'Kitchen', 'Free Parking'],
    geometry: { type: 'Point', coordinates: [75.7720, 13.3161] },
    image: { url: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Tuscany Vineyard Farmhouse',
    description: 'A rustic stone farmhouse surrounded by rolling Chianti vineyards, with a wine cellar and olive press.',
    price: 38000,
    location: 'Greve in Chianti, Tuscany',
    country: 'Italy',
    category: 'Farms',
    maxGuests: 8,
    amenities: ['Wifi', 'Pool', 'Kitchen', 'Free Parking', 'TV'],
    geometry: { type: 'Point', coordinates: [11.3172, 43.5832] },
    image: { url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Tea Garden Bungalow in Assam',
    description: 'Stay in a colonial planter\'s bungalow on a 500-acre tea garden. Includes guided tea-tasting and factory tour.',
    price: 9500,
    location: 'Jorhat, Assam',
    country: 'India',
    category: 'Farms',
    maxGuests: 6,
    amenities: ['Wifi', 'Kitchen', 'Free Parking', 'AC', 'TV'],
    geometry: { type: 'Point', coordinates: [94.2039, 26.7465] },
    image: { url: 'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Lavender Farm Cottage in Provence',
    description: 'A sun-drenched stone cottage surrounded by rows of blooming lavender. Distillery and markets nearby.',
    price: 25000,
    location: 'Valensole, Provence',
    country: 'France',
    category: 'Farms',
    maxGuests: 4,
    amenities: ['Wifi', 'Kitchen', 'Free Parking', 'TV'],
    geometry: { type: 'Point', coordinates: [6.0183, 43.8353] },
    image: { url: 'https://images.unsplash.com/photo-1464638681273-0962e9b53566?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Spice Plantation Retreat in Kerala',
    description: 'Surrounded by cardamom, pepper and nutmeg trees — guided plantation walks, Ayurvedic treatments included.',
    price: 7200,
    location: 'Thekkady, Idukki',
    country: 'India',
    category: 'Farms',
    maxGuests: 4,
    amenities: ['Wifi', 'Kitchen', 'Free Parking', 'AC'],
    geometry: { type: 'Point', coordinates: [77.1561, 9.5998] },
    image: { url: 'https://images.unsplash.com/photo-1596276122653-651a3898309c?w=1200&auto=format&fit=crop', filename: 'seed' },
  },

  // ── ARCTIC ────────────────────────────────────────────────────────────────
  {
    title: 'Glass Igloo in Finnish Lapland',
    description: 'Thermal glass igloo designed for Northern Lights viewing in bed. Husky safari and snowshoe hikes included.',
    price: 68000,
    location: 'Saariselkä, Lapland',
    country: 'Finland',
    category: 'Arctic',
    maxGuests: 2,
    amenities: ['Wifi', 'TV'],
    geometry: { type: 'Point', coordinates: [27.4227, 68.4185] },
    image: { url: 'https://images.unsplash.com/photo-1518616817900-a91eb9dda5e0?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Aurora Lodge in Tromsø',
    description: 'Wilderness lodge above the Arctic Circle with guided Northern Lights experiences and reindeer herding.',
    price: 55000,
    location: 'Tromsø, Troms',
    country: 'Norway',
    category: 'Arctic',
    maxGuests: 4,
    amenities: ['Wifi', 'Kitchen', 'TV'],
    geometry: { type: 'Point', coordinates: [18.9553, 69.6496] },
    image: { url: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Svalbard Expedition Base',
    description: 'A world-away polar expedition base at 78°N, with guided glacier walks, snowmobile tours and polar bear watches.',
    price: 82000,
    location: 'Longyearbyen, Svalbard',
    country: 'Norway',
    category: 'Arctic',
    maxGuests: 6,
    amenities: ['Wifi', 'Kitchen'],
    geometry: { type: 'Point', coordinates: [15.6461, 78.2232] },
    image: { url: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Ice Hotel Suite, Sweden',
    description: 'Hand-sculpted ice suite in the world-famous ICEHOTEL — a new design every winter by international artists.',
    price: 75000,
    location: 'Jukkasjärvi, Lapland',
    country: 'Sweden',
    category: 'Arctic',
    maxGuests: 2,
    amenities: ['TV'],
    geometry: { type: 'Point', coordinates: [20.6101, 67.8557] },
    image: { url: 'https://images.unsplash.com/photo-1477346611705-65d1883cee1e?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Alaskan Wilderness Cabin',
    description: 'Off-grid log cabin on the edge of Denali National Park — moose, caribou and bald eagles at every window.',
    price: 32000,
    location: 'Healy, Denali Borough',
    country: 'USA',
    category: 'Arctic',
    maxGuests: 4,
    amenities: ['Kitchen', 'Free Parking'],
    geometry: { type: 'Point', coordinates: [-148.9653, 63.8657] },
    image: { url: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&auto=format&fit=crop', filename: 'seed' },
  },

  // ── DOMES ─────────────────────────────────────────────────────────────────
  {
    title: 'Stargazing Geodesic Dome in Ladakh',
    description: 'Transparent geodesic dome at 3,500m in the Nubra Valley — fall asleep under the Milky Way in warm comfort.',
    price: 12000,
    location: 'Nubra Valley, Ladakh',
    country: 'India',
    category: 'Domes',
    maxGuests: 2,
    amenities: ['Wifi', 'Free Parking'],
    geometry: { type: 'Point', coordinates: [77.5619, 34.5539] },
    image: { url: 'https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Moroccan Desert Dome',
    description: 'Luxury dome in the Sahara with stargazing telescope, private hot tub and camel trekking at dawn.',
    price: 18000,
    location: 'Merzouga, Erg Chebbi',
    country: 'Morocco',
    category: 'Domes',
    maxGuests: 2,
    amenities: ['Wifi', 'Pool', 'Free Parking'],
    geometry: { type: 'Point', coordinates: [-4.0082, 31.1000] },
    image: { url: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Patagonian Bubble Dome',
    description: 'Sleep inside a crystal bubble at the edge of the Patagonian steppe — guanacos graze outside your dome.',
    price: 52000,
    location: 'Torres del Paine, Magallanes',
    country: 'Chile',
    category: 'Domes',
    maxGuests: 2,
    amenities: ['Wifi', 'TV'],
    geometry: { type: 'Point', coordinates: [-73.0000, -51.0000] },
    image: { url: 'https://images.unsplash.com/photo-1490730141103-6cac27aaab94?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Vineyard Dome Experience, Nashik',
    description: 'Transparent dome in the middle of a working vineyard. Wine-tasting, sunset grape crushing and city convenience.',
    price: 8500,
    location: 'Sula Vineyards, Nashik',
    country: 'India',
    category: 'Domes',
    maxGuests: 2,
    amenities: ['Wifi', 'Pool', 'AC', 'Free Parking'],
    geometry: { type: 'Point', coordinates: [73.7793, 20.0059] },
    image: { url: 'https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Tenerife Volcano Dome',
    description: 'Geodesic dome perched on the volcanic highlands of Teide National Park — sunrise above the clouds.',
    price: 22000,
    location: 'El Teide, Tenerife',
    country: 'Spain',
    category: 'Domes',
    maxGuests: 2,
    amenities: ['Wifi', 'Kitchen', 'Free Parking'],
    geometry: { type: 'Point', coordinates: [-16.6419, 28.2725] },
    image: { url: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=1200&auto=format&fit=crop', filename: 'seed' },
  },

  // ── BOATS ─────────────────────────────────────────────────────────────────
  {
    title: 'Traditional Houseboat on Dal Lake, Srinagar',
    description: 'The classic Kashmir experience — a hand-carved cedar houseboat on the glassy Dal Lake with all meals.',
    price: 6800,
    location: 'Dal Lake, Srinagar',
    country: 'India',
    category: 'Boats',
    maxGuests: 4,
    amenities: ['Wifi', 'Kitchen', 'TV', 'AC'],
    geometry: { type: 'Point', coordinates: [74.8432, 34.0937] },
    image: { url: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Alleppey Rice Boat, Kerala Backwaters',
    description: 'Cruise the emerald backwaters of Kerala on a luxuriously converted rice boat (kettuvallam). Pure bliss.',
    price: 14000,
    location: 'Alappuzha, Kerala',
    country: 'India',
    category: 'Boats',
    maxGuests: 4,
    amenities: ['Wifi', 'Kitchen', 'AC', 'TV'],
    geometry: { type: 'Point', coordinates: [76.3388, 9.4981] },
    image: { url: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Luxury Gulet in Turkish Riviera',
    description: 'Charter a gorgeous 24m wooden gulet with crew around the turquoise coves of Bodrum and Göcek.',
    price: 85000,
    location: 'Bodrum, Muğla',
    country: 'Turkey',
    category: 'Boats',
    maxGuests: 8,
    amenities: ['Wifi', 'Pool', 'Kitchen', 'AC', 'TV'],
    geometry: { type: 'Point', coordinates: [27.4242, 37.0344] },
    image: { url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Amsterdam Canal Houseboat',
    description: 'Live like a local on a charming 1930s houseboat moored on the Prinsengracht, steps from the Anne Frank House.',
    price: 18000,
    location: 'Prinsengracht, Amsterdam',
    country: 'Netherlands',
    category: 'Boats',
    maxGuests: 3,
    amenities: ['Wifi', 'Kitchen', 'TV'],
    geometry: { type: 'Point', coordinates: [4.8820, 52.3746] },
    image: { url: 'https://images.unsplash.com/photo-1584622781564-1d987f7333c1?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
  {
    title: 'Mekong River Floating Villa',
    description: 'A romantic floating villa on the Mekong river near Luang Prabang — watch monks collect alms at sunrise.',
    price: 9500,
    location: 'Luang Prabang, Laos',
    country: 'Laos',
    category: 'Boats',
    maxGuests: 2,
    amenities: ['Wifi', 'Kitchen', 'AC', 'TV'],
    geometry: { type: 'Point', coordinates: [102.1348, 19.8837] },
    image: { url: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=1200&auto=format&fit=crop', filename: 'seed' },
  },
];

// ── Runner ─────────────────────────────────────────────────────────────────
async function main() {
  await mongoose.connect(DB_URL);
  console.log('✅  Connected to Atlas DB');

  // Find the first user in DB to assign as owner (or create with a dummy ID)
  const User = require('../models/user.js');
  const firstUser = await User.findOne({});
  const ownerId = firstUser ? firstUser._id : new mongoose.Types.ObjectId();

  const docs = listings.map(l => ({ ...l, owner: ownerId, status: 'Active' }));

  const result = await Listing.insertMany(docs);
  console.log(`✅  Inserted ${result.length} listings across all 11 categories`);

  await mongoose.disconnect();
  console.log('✅  Done. Disconnected from DB.');
}

main().catch(err => { console.error('❌  Seed failed:', err); process.exit(1); });
