const mongoose = require("mongoose");
const Schema = mongoose.Schema;

// MongoDB Schema representing a User authenticated via Firebase.
const userSchema = new Schema({
    firebaseUid: {
        type: String,
        unique: true,
        sparse: true // Makes it unique but handles legacy data gracefully
    },
    email: {
        type: String,
        required: true,
        unique: true
    },
    fcmTokens: [String],
    username: {
        type: String,
        required: true // Now defined explicitly instead of passively generated by Passport
    },
    image: {
        url: {
            type: String,
            default: "https://images.unsplash.com/photo-1511367461989-f85a21fda167?q=80&w=2831&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
        },
        filename: {
            type: String,
            default: "profile_image"
        }
    },
    bio: {
        type: String,
        default: "Hey there! I am using StayNest."
    },
    wishlist: [
        {
            type: Schema.Types.ObjectId,
            ref: "Listing"
        }
    ],
    isAdmin: {
        type: Boolean,
        default: false
    }
}, { timestamps: true });

// We explicitly DO NOT use `passport-local-mongoose` anymore, 
// because Google sets the password hash security.

module.exports = mongoose.model('User', userSchema);
